name: 🚀 Deploy to Production on Main (via PR)

on:
  pull_request:  # Triggered by Pull Requests
    branches:
      - main     # Specifically when a PR is merged into main

jobs:
  web-deploy-production:
    name: 🎉 Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.merged == true #  Crucial condition!
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
        
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files to Production
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 46.202.145.116
        username: u746034674
        port: 21
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
        server-dir: domains/cultivesmart.com.br/public_html/